### ISSUE TITLE
Can not start the project.

### ISSUE THREAD

**Issue by momolly1024** [smoghal/react-heatmap#1]
After install nodemodules, yarn start will get the error like:

```
λyarn start
yarn run v1.22.18
$ node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from ./
i ｢wds｣: 404s will fallback to /index.html
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\User\Desktop\molly\github\example-pj\react-heatmap\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\User\Desktop\molly\github\example-pj\react-heatmap\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\User\Desktop\molly\github\example-pj\react-heatmap\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\User\Desktop\molly\github\example-pj\react-heatmap\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\User\Desktop\molly\github\example-pj\react-heatmap\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\User\Desktop\molly\github\example-pj\react-heatmap\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\User\Desktop\molly\github\example-pj\react-heatmap\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\User\Desktop\molly\github\example-pj\react-heatmap\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by momolly1024** [comment]
found the problem is Node version, should use 12.12.0 (maybe or early).!

Thx.
